### ISSUE TITLE
__get_ngram_children failed in python

### ISSUE THREAD

**Issue by 9992800** [michaelfester/mastodon#5]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bindict.py", line 449, in get_predictions
    children = self.__get_ngram_children(ngram)
  File "bindict.py", line 319, in __get_ngram_children
    child_weight = self.bytes[child_address + offset_weight]
IndexError: bytearray index out of range

**Comment by sweldon** [comment]
Did you ever figure this out?
